pub mod Errors {
    pub const INSUFFICIENT_BALANCE: felt252 = 'INSUFFICIENT_BALANCE';
    pub const INSUFFICIENT_ALLOWANCE: felt252 = 'INSUFFICIENT_ALLOWANCE';
    pub const ALREADY_EXIST: felt252 = 'ALREADY_EXIST';
    pub const INVALID_CLASSHASH: felt252 = 'INVALID_CLASSHASH';
    pub const UNAUTHORIZED: felt252 = 'UNAUTHORIZED';
    pub const NOT_REGISTERED: felt252 = 'NOT_REGISTERED';
    pub const INVALID_ADDRESS: felt252 = 'INVALID_ADDRESS';
    pub const INVALID_LISTING: felt252 = 'INVALID_LISTING';
    pub const PRICE_TOO_LOW: felt252 = 'PRICE_TOO_LOW';
    pub const INVALID_PARAM: felt252 = 'INVALID_PARAM';
    pub const NOT_FOR_SALE: felt252 = 'NOT_FOR_SALE';
}
